name: Validate rates and outages file
on:
  push:
    paths:
      - rates.yaml
      - outages.yaml
  pull_request:
    paths:
      - rates.yaml
      - outages.yaml

jobs:
  validate-rates-file:
    strategy:
      matrix:
        python-version: [3.12, 3.13]
    name: Validate rates and outages file
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Validate rates and outages file
        run: |
          validate-files -g --rates_file rates.yaml --outages_file outages.yaml
